[default.limits]
json = "1 KiB"

[default]
key = "a default app-key"
extra = false
ident = "Rocket"

[debug]
address = "0.0.0.0"
port = 8000
workers = 1
keep_alive = 0
log_level = "critical"

[release]
address = "0.0.0.0"
port = 17698
workers = 12
keep_alive = 5
log_level = "critical"